### ISSUE TITLE
Puppet 6 support/ stdlib

### ISSUE THREAD

**Issue by schlitzered** [lvicainne/puppet-opendkim#15]
please upgrade the module to allow stdlib 6.x.x, which is needed for puppet 6 support

**Comment by nikdoof** [comment]
#17 has been opened today to "fix" it, but it'll need testing and @lvicainne to merge.

**Comment by lvicainne** [comment]
Hi @schlitzered 
This issue seems solved now following #19 
So, I close it
Louis
