### ISSUE TITLE
Puppet 3 incompatibility

### ISSUE THREAD

**Issue by vanch** [lvicainne/puppet-opendkim#2]
Hi.

You have .each feature in [config.pp](https://github.com/lvicainne/lvicainne-opendkim/blob/master/manifests/config.pp#L97), which is compatible with 3.8 version only with [parser = future](https://docs.puppet.com/puppet/3/reference/experiments_future.html) flag. 
Sometimes, this flag is inappropriate to use (we have big infra on puppet and switching this on would be painful).
It would be great to have some e.g. create_resources analog for older versions.
I don't think you're interested in all that, but I can't be silent :)

You have beautiful module BTW. Thx.

**Comment by lvicainne** [comment]
Hi Vanch,

It could be a good idea indeed to be retro-compatible to Puppet 3 and not using the ".each" feature :-)
However, to be honnest, I am not yet able to manage the "create_resources" feature or to deal with loops without using the ".each" keyword.

So, feel free to fork this module ;-) and I would be very pleased to have a Pull Request from you :-)
Thx,
lvicainne

**Comment by jkroepke** [comment]
Hi,

since https://github.com/lvicainne/puppet-opendkim/pull/5 is merged. You close it as "WONT FIX". :)

**Comment by lvicainne** [comment]
Hello !
Thanks, indeed ;-)
